name = "sandbox-kv"
main = "worker.js"
compatibility_date = "2026-03-16"

[[kv_namespaces]]
binding = "SANDBOX_KV"
id = "5b1e95de1c9a48e8bd40010fef98ef0f"
preview_id = "f14544fa0d3546278c6cc1fe1a1460bf"

