name = "sandbox-kv"
type = "javascript"
account_id = "9dac0d3850f8f5befb922c2e2c614bba"
main = "worker.js"
workers_dev = true
compatibility_date = "2026-03-16"

kv_namespaces = [
  { binding = "KV", id = "055fa0f4d65044229eb54a3d5dcbab4a" }
]