name = "cloudflare"
main = "worker.js"
compatibility_date = "2026-03-16"

[[kv_namespaces]]
binding = "BGP_Sandbox_KV"
id = "3b405a7635014e199b241d45c412fedc"
preview_id = "ff32d753440b4ca5ba11c0185c7828b5"
